# Basic Information 
title: Francesco Pontiggia
position: Ph.D. student
affiliation: TU Wien
affiliation_link: https://informatics.tuwien.ac.at/
affiliation_logo:
email: name.surname(at)tuwien.ac.at

# Search Engine Optimization (SEO)
keywords: Francesco Pontiggia
canonical: 
description: Francesco Pontiggia is a Ph.D. student in model checking.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
#google_scholar: https://scholar.google.com/citations?user=PwC8SMEAAAAJ&hl=it
github_link: https://github.com/francescopont
linkedin: https://linkedin.com/in/fpontiggia
#twitter: 

# Images 
avatar: assets/img/pon.jpg

# Footnotes
#footnote:
#footnote_link:

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
